import { BASE_URL } from "../config.ts";

export function getDiscoveryDocument(): Record<string, unknown> {
  return {
    issuer: BASE_URL,
    jwks_uri: `${BASE_URL}/.well-known/openid-configuration/jwks`,
    authorization_endpoint: `${BASE_URL}/connect/authorize`,
    token_endpoint: `${BASE_URL}/connect/token`,
    userinfo_endpoint: `${BASE_URL}/connect/userinfo`,
    end_session_endpoint: `${BASE_URL}/connect/endsession`,
    check_session_iframe: `${BASE_URL}/connect/checksession`,
    revocation_endpoint: `${BASE_URL}/connect/revocation`,
    introspection_endpoint: `${BASE_URL}/connect/introspect`,
    device_authorization_endpoint: `${BASE_URL}/connect/deviceauthorization`,
    frontchannel_logout_supported: true,
    frontchannel_logout_session_supported: true,
    backchannel_logout_supported: true,
    backchannel_logout_session_supported: true,
    scopes_supported: [
      "openid",
      "profile",
      "efaas.profile",
      "efaas.birthdate",
      "efaas.email",
      "efaas.mobile",
      "efaas.photo",
      "efaas.permanent_address",
      "efaas.current_address",
      "efaas.country",
      "efaas.passport_number",
      "efaas.work_permit_status",
      "offline_access",
    ],
    claims_supported: [
      "sub",
      "name",
      "family_name",
      "given_name",
      "middle_name",
      "nickname",
      "preferred_username",
      "profile",
      "picture",
      "website",
      "gender",
      "birthdate",
      "zoneinfo",
      "locale",
      "updated_at",
      "address",
      "location",
      "email",
      "email_verified",
      "phone_number",
      "fname_dhivehi",
      "lname_dhivehi",
      "user_type",
      "verification_level",
      "user_state",
      "dob",
      "passport_number",
      "is_workpermit_active",
      "idnumber",
      "mname_dhivehi",
      "country_dialing_code",
      "country_code",
      "country_code_alpha3",
      "face_verified",
      "common_name_dhivehi",
      "common_name_english",
      "verified",
      "verification_type",
      "full_name",
      "first_name",
      "last_name",
      "first_name_dhivehi",
      "last_name_dhivehi",
      "middle_name_dhivehi",
      "full_name_dhivehi",
      "user_type_description",
      "last_verified_date",
      "mobile",
      "photo",
      "permanent_address",
      "country_name",
      "previous_passport_number",
    ],
    grant_types_supported: [
      "authorization_code",
      "client_credentials",
      "refresh_token",
      "implicit",
      "urn:ietf:params:oauth:grant-type:device_code",
    ],
    response_types_supported: [
      "code",
      "token",
      "id_token",
      "id_token token",
      "code id_token",
      "code token",
      "code id_token token",
    ],
    response_modes_supported: ["form_post", "query", "fragment"],
    token_endpoint_auth_methods_supported: [
      "client_secret_basic",
      "client_secret_post",
    ],
    id_token_signing_alg_values_supported: ["RS256"],
    subject_types_supported: ["public"],
    code_challenge_methods_supported: ["plain", "S256"],
    request_parameter_supported: true,
  };
}
